### ISSUE TITLE
Voting System!

### ISSUE THREAD

**Issue by rswiernik** [dag10/DJ#9]
I want to be able to directly convert my reddit karma to csh.dj points and vice versa. No but really some sort of satisfaction measurement system would be awesome.

**Comment by dag10** [comment]
Skip-voting is implemented in the dev branch and will be included in the next release.

Here's a screenshot of the feature:

![image](https://cloud.githubusercontent.com/assets/4248810/5954232/d8982894-a762-11e4-8bcc-07f2d3b60fe0.png)

:grinning:

**Comment by dag10** [comment]
I've also now added liking, or thumbs up. It'll be in the next release.

![screen shot 2015-01-29 at 5 19 00 pm](https://cloud.githubusercontent.com/assets/4248810/5967563/295fc4de-a7dc-11e4-95b2-70e860453d51.png)

**Comment by rswiernik** [comment]
I like this quite a bit.
